on:
  push:
    branches:
      - main

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-services.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Поиск измененных сервисов
        id: find-services
        run: |
          ALL_SERVICES=$(find . -maxdepth 2 -name "build.gradle.kts" -exec dirname {} \; | sed 's|^./||' | grep -v "^$")
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          CHANGED_SERVICES=$(echo "$CHANGED_FILES" | awk -F'/' '{print $1}' | sort -u)
          
          SERVICES_TO_TEST=$(echo "$CHANGED_SERVICES" | while read service; do
            if echo "$ALL_SERVICES" | grep -q "^${service}$"; then
              echo "$service"
            fi
          done)
          
          if [ ! -z "$SERVICES_TO_TEST" ]; then
            JSON_ARRAY=$(echo "$SERVICES_TO_TEST" | jq -R -s -c 'split("\n")[:-1]')
            echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT
          else
            echo "matrix=[]" >> $GITHUB_OUTPUT
          fi

  run-tests:
    needs: find-changes
    if: ${{ needs.find-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.find-changes.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Установка JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Настройка Gradle
        uses: gradle/gradle-build-action@v2

      - name: Тестирование ${{ matrix.service }}
        run: |
          if [ -f "${{ matrix.service }}/build.gradle.kts" ]; then
            cd ${{ matrix.service }}
            ./gradlew test
          else
            echo "Error: build.gradle.kts not found in ${{ matrix.service }}"
            exit 1
          fi