on:
  push:
    branches:
      - main

jobs:
  find-changes:
    uses: ./.github/workflows/find-changes.yml

  run-tests:
    needs: find-changes
    if: ${{ needs.find-changes.outputs.matrix != '[]' }}
    uses: ./.github/workflows/run-tests.yml
    with:
      matrix: ${{ needs.find-changes.outputs.matrix }}